// Mocks generated by Mockito 5.4.6 from annotations
// in pokedex/test/viewmodel/pokemon_list_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:pokedex/model/pokemon_detail.dart' as _i3;
import 'package:pokedex/model/pokemon_evolution.dart' as _i4;
import 'package:pokedex/model/pokemon_list.dart' as _i2;
import 'package:pokedex/repository/pokemon_repository.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePokemonList_0 extends _i1.SmartFake implements _i2.PokemonList {
  _FakePokemonList_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePokemonDetail_1 extends _i1.SmartFake implements _i3.PokemonDetail {
  _FakePokemonDetail_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePokemonEvolution_2 extends _i1.SmartFake
    implements _i4.PokemonEvolution {
  _FakePokemonEvolution_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i5.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i7.Future<_i2.PokemonList> fetchPokemons({
    int? limit = 10,
    String? nextUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPokemons, [], {
              #limit: limit,
              #nextUrl: nextUrl,
            }),
            returnValue: _i7.Future<_i2.PokemonList>.value(
              _FakePokemonList_0(
                this,
                Invocation.method(#fetchPokemons, [], {
                  #limit: limit,
                  #nextUrl: nextUrl,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.PokemonList>);

  @override
  _i7.Future<_i3.PokemonDetail> fetchPokemonDetails(int? pokemonId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPokemonDetails, [pokemonId]),
            returnValue: _i7.Future<_i3.PokemonDetail>.value(
              _FakePokemonDetail_1(
                this,
                Invocation.method(#fetchPokemonDetails, [pokemonId]),
              ),
            ),
          )
          as _i7.Future<_i3.PokemonDetail>);

  @override
  _i7.Future<_i4.PokemonEvolution> fetchPokemonEvolution(
    String? evolutionChainUrl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPokemonEvolution, [evolutionChainUrl]),
            returnValue: _i7.Future<_i4.PokemonEvolution>.value(
              _FakePokemonEvolution_2(
                this,
                Invocation.method(#fetchPokemonEvolution, [evolutionChainUrl]),
              ),
            ),
          )
          as _i7.Future<_i4.PokemonEvolution>);
}
